### ISSUE TITLE
Fail to deploy app-service with external-mqtt-trigger profile 

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/app-service-configurable#366]
Deploy [compose file](https://github.com/edgexfoundry/edgex-compose/blob/main/taf/docker-compose-taf-no-secty.yml). 
Check the container logs for edgex-app-external-mqtt-trigger.

The container status is always `Restarting` and found the error in logs.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c0446]

goroutine 1 [running]:
github.com/edgexfoundry/app-functions-sdk-go/v2/internal/trigger/mqtt.(*Trigger).Initialize(0xc000064d80, 0xc000311b10, 0xbeb6d8, 0xc00032afc0, 0x0, 0x5, 0xb205a2, 0x4)
	/go/pkg/mod/github.com/edgexfoundry/app-functions-sdk-go/v2@v2.2.0-dev.9/internal/trigger/mqtt/mqtt.go:71 +0x46
github.com/edgexfoundry/app-functions-sdk-go/v2/internal/app.(*Service).MakeItRun(0xc0002890e0, 0x0, 0x0)
	/go/pkg/mod/github.com/edgexfoundry/app-functions-sdk-go/v2@v2.2.0-dev.9/internal/app/service.go:169 +0x11c
main.main()
	/app/main.go:63 +0x5df
```

**Comment by AlexCuse** [comment]
This looks like a bug in the app SDK itself will open a PR shortly.

**Comment by AlexCuse** [comment]
https://github.com/edgexfoundry/app-functions-sdk-go/pull/1021

**Comment by JamesKButcher** [comment]
Fixed by above PR. Closing
